name: mma-stats
schedule: "0 1 * * *"
start_date: "2026-03-29"
catchup: false

default_connections:
    google_cloud_platform: "db"
    duckdb: "db"
default:
    rerun_cooldown: 300
    type: bq.sql # use duckdb.sql for local, bq.sql for staging and production

retries: 1

# variables: